//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspMVCMeeting.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string LBL_MT_DATE {
            get {
                return ResourceManager.GetString("LBL_MT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string LBL_MT_DESCIPTION {
            get {
                return ResourceManager.GetString("LBL_MT_DESCIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitme Saati.
        /// </summary>
        public static string LBL_MT_FINISH_TIME {
            get {
                return ResourceManager.GetString("LBL_MT_FINISH_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Eden.
        /// </summary>
        public static string LBL_MT_FOLLOWER_USERID {
            get {
                return ResourceManager.GetString("LBL_MT_FOLLOWER_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Yonetici.
        /// </summary>
        public static string LBL_MT_MANAGER {
            get {
                return ResourceManager.GetString("LBL_MT_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No:.
        /// </summary>
        public static string LBL_MT_NO {
            get {
                return ResourceManager.GetString("LBL_MT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer.
        /// </summary>
        public static string LBL_MT_PLACE {
            get {
                return ResourceManager.GetString("LBL_MT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod 1.
        /// </summary>
        public static string LBL_MT_SCODE1 {
            get {
                return ResourceManager.GetString("LBL_MT_SCODE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod 2.
        /// </summary>
        public static string LBL_MT_SCODE2 {
            get {
                return ResourceManager.GetString("LBL_MT_SCODE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod 3.
        /// </summary>
        public static string LBL_MT_SCODE3 {
            get {
                return ResourceManager.GetString("LBL_MT_SCODE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod 4.
        /// </summary>
        public static string LBL_MT_SCODE4 {
            get {
                return ResourceManager.GetString("LBL_MT_SCODE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod 5.
        /// </summary>
        public static string LBL_MT_SCODE5 {
            get {
                return ResourceManager.GetString("LBL_MT_SCODE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlama Saati.
        /// </summary>
        public static string LBL_MT_START_TIME {
            get {
                return ResourceManager.GetString("LBL_MT_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string LBL_MT_STS {
            get {
                return ResourceManager.GetString("LBL_MT_STS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglar.
        /// </summary>
        public static string LBL_MT_TAGS {
            get {
                return ResourceManager.GetString("LBL_MT_TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string LBL_MT_TITLE {
            get {
                return ResourceManager.GetString("LBL_MT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplanti Turu.
        /// </summary>
        public static string LBL_MT_TYPE {
            get {
                return ResourceManager.GetString("LBL_MT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirilecekler.
        /// </summary>
        public static string LBL_MT_USER_CC {
            get {
                return ResourceManager.GetString("LBL_MT_USER_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum Dışı Katılımcılar.
        /// </summary>
        public static string LBL_MT_USER_OUT {
            get {
                return ResourceManager.GetString("LBL_MT_USER_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katılımcılar.
        /// </summary>
        public static string LBL_MT_USER_PARTICIPANTS {
            get {
                return ResourceManager.GetString("LBL_MT_USER_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyid Eden.
        /// </summary>
        public static string LBL_MTL_CONFIRMER {
            get {
                return ResourceManager.GetString("LBL_MTL_CONFIRMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karar Türü.
        /// </summary>
        public static string LBL_MTL_DECISION_TYPE {
            get {
                return ResourceManager.GetString("LBL_MTL_DECISION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman.
        /// </summary>
        public static string LBL_MTL_DEPARTMENT {
            get {
                return ResourceManager.GetString("LBL_MTL_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        public static string LBL_MTL_EXECUTANT {
            get {
                return ResourceManager.GetString("LBL_MTL_EXECUTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitme Tarihi.
        /// </summary>
        public static string LBL_MTL_FINISH_DATE {
            get {
                return ResourceManager.GetString("LBL_MTL_FINISH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Uygun mu.
        /// </summary>
        public static string LBL_MTL_OFFER_OK {
            get {
                return ResourceManager.GetString("LBL_MTL_OFFER_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Eden.
        /// </summary>
        public static string LBL_MTL_OFFER_USER {
            get {
                return ResourceManager.GetString("LBL_MTL_OFFER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Kodu.
        /// </summary>
        public static string LBL_MTL_PROJECT_CODE {
            get {
                return ResourceManager.GetString("LBL_MTL_PROJECT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlı Oldugu Form Açıklama.
        /// </summary>
        public static string LBL_MTL_RELATED_FORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("LBL_MTL_RELATED_FORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlı Olduğu Form.
        /// </summary>
        public static string LBL_MTL_RELATED_FORM_REF {
            get {
                return ResourceManager.GetString("LBL_MTL_RELATED_FORM_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu.
        /// </summary>
        public static string LBL_MTL_RESPONSIBLE {
            get {
                return ResourceManager.GetString("LBL_MTL_RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlama Tarihi.
        /// </summary>
        public static string LBL_MTL_START_DATE {
            get {
                return ResourceManager.GetString("LBL_MTL_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Türü.
        /// </summary>
        public static string LBL_MTL_TYPE {
            get {
                return ResourceManager.GetString("LBL_MTL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe.
        /// </summary>
        public static string LBL_PRJ_BUDGET {
            get {
                return ResourceManager.GetString("LBL_PRJ_BUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string LBL_PRJ_BUDGET_CURRENCY {
            get {
                return ResourceManager.GetString("LBL_PRJ_BUDGET_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project code.
        /// </summary>
        public static string LBL_PRJ_CODE {
            get {
                return ResourceManager.GetString("LBL_PRJ_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam/Gün sayı.
        /// </summary>
        public static string LBL_PRJ_MAN_DAY {
            get {
                return ResourceManager.GetString("LBL_PRJ_MAN_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        public static string LBL_PRJ_MEMBERS {
            get {
                return ResourceManager.GetString("LBL_PRJ_MEMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Adı.
        /// </summary>
        public static string LBL_PRJ_NAME {
            get {
                return ResourceManager.GetString("LBL_PRJ_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Durumu.
        /// </summary>
        public static string LBL_PRJ_STS {
            get {
                return ResourceManager.GetString("LBL_PRJ_STS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiyon.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
    }
}
