//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public int ID { get; set; }
        public string prb_kod { get; set; }
        public string prb_tanim { get; set; }
        public Nullable<bool> prb_ana_para { get; set; }
        public Nullable<int> prb_sira { get; set; }
        public Nullable<bool> prb_aktif { get; set; }
        public string prb_SAP_para_birimi { get; set; }
        public string prb_unity_para_birimi { get; set; }
    }
}
