//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_LOG
    {
        public int ID { get; set; }
        public Nullable<int> MLS_MLG_REF { get; set; }
        public Nullable<System.DateTime> MLS_CREATE_DATE { get; set; }
        public string MLS_CREATE_USERID { get; set; }
        public string MLS_IP { get; set; }
        public string MLS_DESCRIPTION { get; set; }
        public string MLS_BROWSER { get; set; }
    }
}
