//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_NOTIFICATIONS
    {
        public int ID { get; set; }
        public int NTF_REFID { get; set; }
        public string NTF_USERID { get; set; }
        public Nullable<bool> NTF_READ { get; set; }
        public Nullable<bool> NTF_SEEN { get; set; }
        public Nullable<bool> NTF_DELETED { get; set; }
        public Nullable<System.DateTime> NTF_DELETED_DATE { get; set; }
        public Nullable<System.DateTime> NTF_CREATEDATE { get; set; }
    }
}
