//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_PROJECTS
    {
        public int ID { get; set; }
        public string PRJ_CODE { get; set; }
        public string PRJ_NAME { get; set; }
        public Nullable<System.DateTime> PRJ_START_DATE { get; set; }
        public Nullable<System.DateTime> PRJ_FINISH_DATE { get; set; }
        public string PRJ_RESPONSIBLE { get; set; }
        public string PRJ_MEMBERS { get; set; }
        public Nullable<double> PRJ_BUDGET { get; set; }
        public Nullable<int> PRJ_BUDGET_CURRENCY { get; set; }
        public Nullable<int> PRJ_MAN_DAY { get; set; }
        public string PRJ_DEPARTMENT { get; set; }
        public Nullable<System.DateTime> PRJ_CREATEDATE { get; set; }
        public string PRJ_CREATE_USERID { get; set; }
        public Nullable<System.DateTime> PRJ_UPDATEDATE { get; set; }
        public string PRJ_UPDATE_USERID { get; set; }
        public Nullable<bool> PRJ_STS { get; set; }
    }
}
