//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_STATUS
    {
        public int ID { get; set; }
        public string MST_NAME { get; set; }
        public Nullable<int> MST_TYPE { get; set; }
        public Nullable<bool> MST_ACTIVE { get; set; }
    }
}
