//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_FILE_CATEGORY
    {
        public int ID { get; set; }
        public string MFC_NAME { get; set; }
        public Nullable<bool> MFC_ACTIVE { get; set; }
    }
}
