//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_PARTICIPANTS
    {
        public int ID { get; set; }
        public Nullable<int> MTP_REF { get; set; }
        public string MTP_USER { get; set; }
        public Nullable<int> MTP_TYPE { get; set; }
        public Nullable<System.DateTime> MTP_CREATEDATE { get; set; }
        public string MTP_CREATE_USERID { get; set; }
    }
}
