//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING_FILES
    {
        public int ID { get; set; }
        public Nullable<int> MTF_MT_REF { get; set; }
        public Nullable<int> MTF_TYPE { get; set; }
        public Nullable<int> MTF_CATEGORY { get; set; }
        public string MTF_FILENAME { get; set; }
        public Nullable<System.DateTime> MTF_CREATEDATE { get; set; }
        public string MTF_CREATE_USERID { get; set; }
        public string MTF_DESCRIPTION { get; set; }
    }
}
