//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVCMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MEETING_LINE
    {
        public int ID { get; set; }
        public string MT_TITLE { get; set; }
        public string MTL_DESCRIPTION { get; set; }
    }
}
